apiVersion: v1
kind: ConfigMap
metadata:
  name: mirror-serve-rsync-config
  namespace: mirror
data:
  rsyncd.conf: |-
    uid = nobody
    gid = nobody
    use chroot = yes
    motd file = /tmp/motd

    [share]
    path = /data/share/
    comment = Share
    read only = yes
    refuse options = c delete
    list = yes

    [archlinux]
    path = /data/share/archlinux
    comment = Share
    read only = yes
    refuse options = c delete
    list = yes