apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirror-cron-rsync
  namespace: mirror-sg
  labels:
    app: mirror-cron-rsync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mirror-cron-rsync
  template:
    metadata:
      labels:
        app: mirror-cron-rsync
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: mirror-cron-rsync
        image: narapon/mirror-rsync:2024.01.21.6
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "1"
            memory: "50Mi"
          limits:
            cpu: "6"
            memory: "2000Mi"
        volumeMounts:
        - name: longhorn-mirror
          mountPath: /mnt/mirror
        - name: longhorn-mirror-logs
          mountPath: /mnt/mirror_logs
      imagePullSecrets:
      - name: dockersecret
      volumes:
      - name: longhorn-mirror
        persistentVolumeClaim:
          claimName: mirror-pvc
      - name: longhorn-mirror-logs
        persistentVolumeClaim:
          claimName: mirror-logs-pvc
