apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirror-cron-rsync
  namespace: mirror
  labels:
    app: mirror-cron-rsync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mirror-cron-rsync
  template:
    metadata:
      labels:
        app: mirror-cron-rsync
    spec:
      containers:
      - name: mirror-cron-rsync
        image: narapon/mirror-rsync:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1"
            memory: "50Mi"
          limits:
            cpu: "4"
            memory: "2000Mi"
        volumeMounts:
        - name: nfs-mirror
          mountPath: /mnt/mirror
        - name: nfs-mirror-logs
          mountPath: /mnt/mirror_logs
      imagePullSecrets:
      - name: dockersecret
      volumes:
      - name: nfs-mirror
        nfs:
          server: 192.168.10.10
          path: /docker_mounts/mirror
      - name: nfs-mirror-logs
        nfs:
          server: 192.168.10.10
          path: /docker_mounts/mirror_logs