apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirror-serve-rsync
  namespace: production
  labels:
    app: mirror-serve-rsync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mirror-serve-rsync
  template:
    metadata:
      labels:
        app: mirror-serve-rsync
    spec:
      containers:
      - name: mirror-serve-rsync
        image: toendeavour/rsyncd-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 873
          name: rsync
        resources:
            requests:
              cpu: "200m"
              memory: "50Mi"
            limits:
              cpu: "4"
              memory: "1000Mi"
        volumeMounts:
        - name: nfs-mirror-serve-rsync-data
          mountPath: /data/share
        - name: mirror-serve-rsync-config
          mountPath: /config
      imagePullSecrets:
      - name: dockersecret
      volumes:
      - name: mirror-serve-rsync-config
        configMap:
          name: mirror-serve-rsync-config
      - name: nfs-mirror-serve-rsync-data
        nfs:
          server: ${NFS_IP}
          path: /docker_mounts/mirror
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: mirror-serve-rsync
  name: mirror-serve-rsync
  namespace: production
spec:
  ports:
  - port: 873
    targetPort: 873
    protocol: TCP
    name: http
  selector:
    app: mirror-serve-rsync
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mirror-serve-rsync
  namespace: production
spec:
  host: mirror-serve-rsync
  trafficPolicy:
    tls:
      mode: DISABLE