apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mirror-serve
  namespace: mirror
spec:
  hosts:
  - "mirror.kst.asia"
  gateways:
  - kst-asia-gateway
  tcp:
  - match:
    - port: 873
    route:
    - destination:
        host: mirror-serve-rsync
        port:
          number: 873
      weight: 100
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: mirror-serve-nginx
        port:
          number: 80
      weight: 100
  